name = "app-turso-remix-cloudflare"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"
compatibility_flags = ["streams_enable_constructors"]

[site]
  bucket = "./public"

[build]
  command = "npm run build"

[vars]
  TURSO_DB_URL = "https://fast-commerce-xinnks.turso.io"